use serde::{Deserialize, Serialize};
use std::path::Path;
use chrono::{DateTime, Utc};

/// Represents a single phase of a multi-phase construction mission (PESP v2).
/// Each phase has a clear goal, required files, and a success criterion.
#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct Fase {
    /// Phase number (1-based)
    pub numero: u32,
    /// Short description, e.g. "Crear estructura base de archivos"
    pub descripcion: String,
    /// Files this phase must create or modify
    pub archivos: Vec<String>,
    /// Acceptance criterion — what the Critic checks to consider this phase done
    pub criterio_de_exito: String,
    /// Status: "PENDIENTE" | "EN_PROGRESO" | "COMPLETADA" | "FALLIDA"
    pub estado: String,
}

/// Represents a single atomic unit of work within a complex project.
/// Each micro-goal maps to one or a few tightly related files.
#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct MicroMeta {
    /// Short description of this goal, e.g. "Implement board.py with 64 real squares"
    pub descripcion: String,
    /// Files this micro-goal must create or modify
    pub archivos: Vec<String>,
    /// Expected interface/contract (function signatures) for verification
    pub contrato: String,
    /// Status: "PENDIENTE" | "EN_PROGRESO" | "COMPLETADA" | "VERIFICADA"
    pub estado: String,
}

/// Persistent session state saved to `{workspace}/.aura_session.json` after each agent step.
/// Survives laptop sleep/hibernate/restart cycles.
#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct SessionJournal {
    /// Sprint 2: Unique identifier for this mission session.
    /// Generated automatically on mission start. Survives restarts.
    #[serde(default)]
    pub session_id: String,
    /// Sprint 2: session_id of the previous session this continues from.
    /// None = brand new mission. Some(id) = continuation/retry.
    #[serde(default)]
    pub parent_session: Option<String>,
    /// The original user objective for this mission
    pub objetivo: String,
    /// Last step number completed
    pub ultimo_paso: u32,
    /// Short description of what was done last
    pub ultimo_estado: String,
    /// Status tag: "EN_PROGRESO", "COMPLETADO", "FALLIDO", "ESPERANDO"
    pub status: String,
    /// Tools used so far (for quick summary)
    pub herramientas_usadas: Vec<String>,
    /// Files touched/created this session
    pub archivos_tocados: Vec<String>,
    /// ISO 8601 timestamp of last update
    pub ultima_actualizacion: String,
    /// Workspace path (so we can reconstruct on boot)
    pub workspace_path: String,
    /// Short-term conversational memory to maintain context
    #[serde(default)]
    pub chat_history: Vec<String>,
    /// List of micro-goals for complex multi-file projects (PESP Protocol)
    #[serde(default)]
    pub micro_metas: Vec<MicroMeta>,
    /// Index of the micro-goal currently in progress (0-based)
    #[serde(default)]
    pub micro_meta_actual: usize,

    // ═══════════════════════════════════════════════════════
    // PESP v2 — Phased Execution System
    // ═══════════════════════════════════════════════════════
    /// Full list of phases generated by the Phase Architect at mission start
    #[serde(default)]
    pub fases: Vec<Fase>,
    /// Index of the phase currently being executed (0-based)
    #[serde(default)]
    pub fase_actual: usize,
    /// Whether a phase plan has already been generated for this mission
    #[serde(default)]
    pub plan_generado: bool,

    // ═══════════════════════════════════════════════════════════
    // MISSION PERSISTENCE — FSM State Snapshots (Fase 1)
    // ═══════════════════════════════════════════════════════════
    /// Serialized current_context string at last checkpoint (for FSM resume)
    #[serde(default)]
    pub fsm_context: Option<String>,
    /// Active FSM role at last checkpoint: "Planner" | "Executor" | "Critic"
    #[serde(default)]
    pub fsm_role: Option<String>,
    /// Step number at last checkpoint
    #[serde(default)]
    pub fsm_step: u32,
    /// If true, this session was interrupted mid-loop and should be offered for resume
    #[serde(default)]
    pub interrupted: bool,
}

/// File name for the session journal (hidden by convention via leading dot)
const JOURNAL_FILE: &str = ".aura_session.json";

/// Generates a robust UUID v4 session ID
fn new_session_id() -> String {
    uuid::Uuid::new_v4().to_string()
}

/// Loads the session journal from disk, or returns a default empty one.
/// Auto-assigns UUID session_id if the loaded journal has none (backwards compat).
pub fn load_journal(workspace_path: &str) -> SessionJournal {
    let journal_path = Path::new(workspace_path).join(JOURNAL_FILE);
    crate::core::hide_file_windows_sync(&journal_path);
    let mut journal = match std::fs::read_to_string(&journal_path) {
        Ok(content) => {
            let clean = content.trim_start_matches('\u{feff}');
            serde_json::from_str(clean).unwrap_or_default()
        },
        Err(_) => SessionJournal::default(),
    };
    if journal.session_id.is_empty() {
        journal.session_id = new_session_id();
    }
    journal
}

/// Saves the session journal atomically: write → fsync → rename.
/// Returns Err if any step fails — checkpoint loss is a FATAL event, not a silent no-op.
pub fn save_journal(workspace_path: &str, journal: &SessionJournal) -> Result<(), String> {
    use std::io::Write;
    let journal_path = Path::new(workspace_path).join(JOURNAL_FILE);
    let tmp_path = Path::new(workspace_path).join(format!("{}.tmp", JOURNAL_FILE));
    let json = serde_json::to_string_pretty(journal)
        .map_err(|e| format!("[JOURNAL] serialize error: {}", e))?;
    {
        let mut f = std::fs::File::create(&tmp_path)
            .map_err(|e| format!("[JOURNAL] create tmp: {}", e))?;
        f.write_all(json.as_bytes())
            .map_err(|e| format!("[JOURNAL] write: {}", e))?;
        f.sync_all()
            .map_err(|e| format!("[JOURNAL] fsync: {}", e))?;
    }
    crate::core::learning::persistence::atomic_replace_sync(&tmp_path, &journal_path)
        .map_err(|e| format!("[JOURNAL] rename: {}", e))?;
    crate::core::hide_file_windows_sync(&journal_path);
    Ok(())
}

/// Builds a human-readable status report from the journal.
/// Called by the meta-command handler — no LLM needed.
pub fn build_status_report(journal: &SessionJournal) -> String {
    if journal.objetivo.is_empty() {
        return "📋 No hay ninguna tarea activa registrada en este workspace.\n\
                El sistema no tiene memoria de misiones anteriores aquí.\n\
                Puedes darme una nueva instrucción cuando quieras."
            .to_string();
    }

    let status_icon = match journal.status.as_str() {
        "COMPLETADO" => "✅",
        "FALLIDO"    => "❌",
        "ESPERANDO"  => "⏸️",
        _            => "🔄", // EN_PROGRESO
    };

    let herramientas = if journal.herramientas_usadas.is_empty() {
        "ninguna aún".to_string()
    } else {
        // De-duplicate and join
        let mut seen = std::collections::HashSet::new();
        journal
            .herramientas_usadas
            .iter()
            .filter(|t| seen.insert(t.to_lowercase()))
            .cloned()
            .collect::<Vec<_>>()
            .join(", ")
    };

    let archivos = if journal.archivos_tocados.is_empty() {
        "ninguno".to_string()
    } else {
        journal
            .archivos_tocados
            .iter()
            .map(|p| {
                // Show just the relative filename for brevity
                Path::new(p)
                    .file_name()
                    .map(|n| n.to_string_lossy().to_string())
                    .unwrap_or_else(|| p.clone())
            })
            .collect::<Vec<_>>()
            .join(", ")
    };

    format!(
        "{status_icon} **Estado de la Misión**\n\
         ─────────────────────────────────\n\
         🎯 **Objetivo:** {objetivo}\n\
         📊 **Estado:** {status}\n\
         🔢 **Último paso completado:** {paso}\n\
         🕐 **Última actualización:** {ts}\n\
         🛠️  **Herramientas usadas:** {herramientas}\n\
         📁 **Archivos tocados:** {archivos}\n\
         ─────────────────────────────────\n\
         💡 *Para continuar desde donde lo dejé, dime: \"continúa\" o \"retoma la tarea\".*",
        status_icon = status_icon,
        objetivo = journal.objetivo,
        status = journal.status,
        paso = journal.ultimo_paso,
        ts = journal.ultima_actualizacion,
        herramientas = herramientas,
        archivos = archivos,
    )
}

/// Updates an existing journal with new step data. Call from `run_agent_loop` each step.
pub fn update_journal(
    journal: &mut SessionJournal,
    paso: u32,
    estado: &str,
    herramienta: &str,
    archivos: &[String],
    workspace_path: &str,
) {
    journal.ultimo_paso = paso;
    journal.ultimo_estado = estado.to_string();
    journal.status = "EN_PROGRESO".to_string();
    journal.workspace_path = workspace_path.to_string();
    journal.ultima_actualizacion = current_timestamp();

    if !herramienta.is_empty() && !journal.herramientas_usadas.contains(&herramienta.to_string()) {
        journal.herramientas_usadas.push(herramienta.to_string());
    }
    for archivo in archivos {
        if !journal.archivos_tocados.contains(archivo) {
            journal.archivos_tocados.push(archivo.clone());
        }
    }
}

/// Marks the mission as completed or failed.
/// Returns Err if persistence fails — callers must treat this as a FATAL event.
pub fn close_journal(journal: &mut SessionJournal, status: &str, workspace_path: &str) -> Result<(), String> {
    journal.status = status.to_string();
    journal.ultima_actualizacion = current_timestamp();
    save_journal(workspace_path, journal)
        .map_err(|e| format!("[CHECKPOINT FATAL] close_journal: {}", e))
}

fn current_timestamp() -> String {
    let now: DateTime<Utc> = Utc::now();
    now.format("%Y-%m-%d %H:%M:%S UTC").to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// H-16: save_journal() fails visibly with invalid path.
    /// Verifies checkpoint failure is NEVER silently discarded.
    #[test]
    fn test_save_journal_fails_visibly_on_invalid_path() {
        let journal = SessionJournal::default();
        // Use a path that cannot exist on any OS
        let result = save_journal("Z:\\nonexistent\\cannot\\exist\\path", &journal);
        assert!(result.is_err(), "save_journal must return Err on invalid path");
        let err_msg = result.unwrap_err();
        assert!(
            err_msg.contains("[JOURNAL]"),
            "Error must include [JOURNAL] prefix for traceability, got: {}", err_msg
        );
    }
}

pub fn start_new_mission(workspace_path: &str, objective: &str) -> Result<SessionJournal, String> {
    let mut journal = SessionJournal::default();
    journal.session_id = new_session_id();
    journal.objetivo = objective.to_string();
    journal.workspace_path = workspace_path.to_string();
    journal.status = "EN_PROGRESO".to_string();
    journal.ultima_actualizacion = current_timestamp();
    // Start totally clean
    journal.fsm_context = None;
    journal.fsm_role = None;
    journal.fsm_step = 0;
    journal.interrupted = false;
    journal.fases.clear();
    journal.micro_metas.clear();
    
    save_journal(workspace_path, &journal)?;
    Ok(journal)
}

pub fn resume_existing_mission(workspace_path: &str) -> Result<SessionJournal, String> {
    let mut journal = load_journal(workspace_path);
    if !journal.interrupted {
        // If not explicitly interrupted, we are forcing a resume of an old state,
        // so we start a new session ID but link the parent
        let old_id = journal.session_id.clone();
        journal.parent_session = Some(old_id);
        journal.session_id = new_session_id();
    }
    journal.status = "EN_PROGRESO".to_string();
    journal.interrupted = false; // We are actively resuming now
    journal.ultima_actualizacion = current_timestamp();
    save_journal(workspace_path, &journal)?;
    Ok(journal)
}

