use std::path::Path;
use tokio::process::Command;
use std::process::Stdio;

/// The result of a test run.
pub enum TestResult {
    NoTests,          // No test framework detected — do nothing, don't revert
    Passed(String),   // Tests ran and passed
    Failed(String),   // Tests ran and actually failed
}

// ── Manifest helpers ─────────────────────────────────────────────────────────

/// If the workspace has JS/TS source files but no `package.json`, creates a
/// minimal one so that npm-based tools don't immediately fail with ENOENT.
fn ensure_package_json(workspace: &Path) {
    let pkg = workspace.join("package.json");
    if pkg.exists() {
        return;
    }

    // Look for .js / .ts files to confirm it really is a JS project
    let has_js = std::fs::read_dir(workspace)
        .map(|rd| {
            rd.flatten().any(|e| {
                let p = e.path();
                matches!(
                    p.extension().and_then(|x| x.to_str()),
                    Some("js") | Some("ts") | Some("mjs") | Some("cjs")
                )
            })
        })
        .unwrap_or(false);

    if !has_js {
        return;
    }

    let minimal = r#"{
  "name": "aura-project",
  "version": "1.0.0",
  "description": "Auto-generated by Aura-Sentinel",
  "scripts": {
    "test": "echo \"No test script configured yet\" && exit 1"
  }
}
"#;
    if let Err(e) = std::fs::write(&pkg, minimal) {
        eprintln!("[TESTER] Warning: could not write minimal package.json: {}", e);
    } else {
        eprintln!("[TESTER] Auto-generated minimal package.json for JS/TS project.");
    }
}

/// If the workspace has Hardhat-related files but no `hardhat.config.js`,
/// creates a minimal Hardhat config so the test runner can start.
fn ensure_hardhat_config(workspace: &Path) {
    let config_js = workspace.join("hardhat.config.js");
    let config_ts = workspace.join("hardhat.config.ts");
    if config_js.exists() || config_ts.exists() {
        return;
    }

    // Detect Hardhat: package.json mentions "hardhat", OR contracts/ directory exists
    let is_hardhat = {
        let pkg_path = workspace.join("package.json");
        let from_pkg = std::fs::read_to_string(&pkg_path)
            .map(|s| s.contains("hardhat"))
            .unwrap_or(false);
        let has_contracts = workspace.join("contracts").is_dir();
        from_pkg || has_contracts
    };

    if !is_hardhat {
        return;
    }

    // CJS-compatible config (works with Hardhat 2.x CommonJS projects)
    let minimal_cfg = r#"require("@nomicfoundation/hardhat-toolbox");

/** @type import('hardhat/config').HardhatUserConfig */
module.exports = {
  solidity: "0.8.20",
};
"#;
    if let Err(e) = std::fs::write(&config_js, minimal_cfg) {
        eprintln!("[TESTER] Warning: could not write minimal hardhat.config.js: {}", e);
    } else {
        eprintln!("[TESTER] Auto-generated minimal hardhat.config.js.");
    }
}

/// Detects if Hardhat v3+ is installed (which requires ESM) and appends an error hint
/// to the context so the LLM can use TOOL_TERMINAL to downgrade to v2.
fn check_hardhat_version_compat(workspace: &Path) -> Option<String> {
    let pkg = workspace.join("package.json");
    if !pkg.exists() { return None; }
    let content = std::fs::read_to_string(&pkg).ok()?;
    // Rough check: "hardhat": "^3 or "hardhat": "3.
    if content.contains("\"hardhat\": \"^3") || content.contains("\"hardhat\": \"3.") {
        return Some(
            "[AVISO CRITICO DE ENTORNO] Se detecto Hardhat v3 instalado. \
            Hardhat v3 requiere proyectos ESM y el codigo \
            generado usa CommonJS. Esto causa el error HHE22. \
            SOLUCION OBLIGATORIA: Usa TOOL_TERMINAL con el comando: \
            'npm install --save-dev hardhat@^2.22.15 @nomicfoundation/hardhat-toolbox@^4.0.0'".to_string()
        );
    }
    None
}

/// If the workspace has Go source files but no `go.mod`, creates a minimal one.
fn ensure_go_mod(workspace: &Path) {
    let go_mod = workspace.join("go.mod");
    if go_mod.exists() {
        return;
    }

    let has_go = std::fs::read_dir(workspace)
        .map(|rd| {
            rd.flatten().any(|e| {
                e.path().extension().and_then(|x| x.to_str()) == Some("go")
            })
        })
        .unwrap_or(false);

    if !has_go {
        return;
    }

    let minimal = "module aura-project\n\ngo 1.21\n";
    if let Err(e) = std::fs::write(&go_mod, minimal) {
        eprintln!("[TESTER] Warning: could not write minimal go.mod: {}", e);
    } else {
        eprintln!("[TESTER] Auto-generated minimal go.mod for Go project.");
    }
}

// ── Bootstrap: run all manifest auto-generators before language detection ────

fn bootstrap_manifests(workspace: &Path) -> Option<String> {
    ensure_package_json(workspace);
    ensure_hardhat_config(workspace);
    ensure_go_mod(workspace);
    check_hardhat_version_compat(workspace)
}

// ── Main test runner ─────────────────────────────────────────────────────────

/// Detects the testing framework and runs the appropriate test suite.
///
/// Before detection, auto-generates any missing manifest files (package.json,
/// hardhat.config.js, go.mod) so the language detector has a cleaner signal.
pub async fn run_tests(workspace_path: &str) -> TestResult {
    let path = Path::new(workspace_path);

    // ── Pre-flight: ensure manifests exist ───────────────────────────────────
    if let Some(compat_warning) = bootstrap_manifests(path) {
        // Hardhat v3 detected — fail fast with actionable error instead of wasting time
        return TestResult::Failed(compat_warning);
    }

    // ── Language + test-framework detection ──────────────────────────────────
    if let Some(lang_config) = crate::core::languages::detect_language(path) {
        let (cmd, args) = lang_config.test_cmd;

        emit_tester_info(&format!(
            "[TESTER] Detected language: {}. Running: {} {}",
            lang_config.name,
            cmd,
            args.join(" ")
        ));

        let output = Command::new(cmd)
            .args(&args)
            .current_dir(workspace_path)
            .stdin(Stdio::null())
            .output()
            .await;

        match output {
            // Binary not found → surface as ENV_FAILURE so agent.rs can auto-install
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                return TestResult::Failed(format!(
                    "[ENV_FAILURE] No se encontró el comando '{}'. \
                     El sistema intentará instalarlo automáticamente.",
                    cmd
                ));
            }
            Err(e) => {
                return TestResult::Failed(format!(
                    "Error ejecutando test de {}: {}",
                    lang_config.name, e
                ));
            }
            Ok(output) => {
                let stdout = String::from_utf8_lossy(&output.stdout).to_string();
                let stderr = String::from_utf8_lossy(&output.stderr).to_string();

                if output.status.success() {
                    return TestResult::Passed(format!(
                        "{} — Pruebas completadas con éxito:\n{}",
                        lang_config.name, stdout
                    ));
                } else {
                    // Combine stdout+stderr so the agent sees the full picture
                    let combined = format!(
                        "{} — Tests fallaron:\n{}\n{}",
                        lang_config.name,
                        stdout.trim(),
                        stderr.trim()
                    )
                    .trim()
                    .to_string();
                    return TestResult::Failed(combined);
                }
            }
        }
    }

    // No language / test framework detected even after manifest bootstrap
    TestResult::NoTests
}

fn emit_tester_info(msg: &str) {
    println!("{}", msg);
}
