use xcap::Monitor;
use base64::{Engine as _, engine::general_purpose::STANDARD};
use serde_json::json;

/// Check if a vision model is available in local Ollama.
/// Returns the first available model name, or None if none are installed.
async fn find_vision_model() -> Option<String> {
    let candidates = ["moondream", "llava", "llama3.2-vision", "llava-phi3", "bakllava"];
    let client = reqwest::Client::new();
    if let Ok(res) = client.get("http://127.0.0.1:11434/api/tags").send().await {
        if let Ok(body) = res.text().await {
            for candidate in &candidates {
                if body.contains(candidate) {
                    return Some(candidate.to_string());
                }
            }
        }
    }
    None
}

async fn capture_headless_browser(url: &str) -> Result<String, String> {
    #[cfg(target_os = "windows")]
    {
        let temp_dir = std::env::temp_dir();
        let screenshot_path = temp_dir.join(format!("aura_vision_{}.png", uuid::Uuid::new_v4()));
        let screenshot_path_str = screenshot_path.to_string_lossy().to_string();

        let edge_path = "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe";
        let chrome_path = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";
        
        let browser_path = if std::path::Path::new(edge_path).exists() {
            edge_path
        } else if std::path::Path::new(chrome_path).exists() {
            chrome_path
        } else {
            return Err("No compatible browser (Edge/Chrome) found for headless capture".to_string());
        };

        // Run headless browser with virtual-time-budget to allow JS/Canvas to render
        let status = tokio::process::Command::new(browser_path)
            .args(&[
                "--headless",
                &format!("--screenshot={}", screenshot_path_str),
                "--window-size=1280,1024",
                "--virtual-time-budget=3000", // Wait 3000ms for Canvas/JS to draw
                url
            ])
            .status()
            .await
            .map_err(|e| format!("Failed to spawn browser: {}", e))?;

        if !status.success() {
            return Err(format!("Browser exited with status: {}", status));
        }

        if !screenshot_path.exists() {
            return Err("Screenshot file was not generated by browser".to_string());
        }

        // Read bytes
        let bytes = tokio::fs::read(&screenshot_path).await.map_err(|e| format!("Failed to read screenshot: {}", e))?;
        // Cleanup
        let _ = tokio::fs::remove_file(&screenshot_path).await;
        
        Ok(STANDARD.encode(&bytes))
    }
    #[cfg(not(target_os = "windows"))]
    {
        Err("Headless capture currently only implemented natively for Windows".to_string())
    }
}

pub async fn evaluate_vision(prompt: &str, use_advanced_model: bool, target_url: Option<&str>) -> Result<String, String> {
    // ── Check if a vision model is available ─────────────────────────────────
    let vision_model = if use_advanced_model {
        find_vision_model().await.filter(|m| m.contains("llama3.2") || m.contains("llava"))
            .or_else(|| Some("llama3.2-vision".to_string()))
    } else {
        find_vision_model().await
    };

        if vision_model.is_none() {
        // FALLO DE VISION: El sistema no debe simular el exito si no tiene ojos.
        let fallback_msg = format!(
            "[FALLO DE VISION CRITICO - Sin modelo instalado]
\
            El agente ha intentado verificar la Interfaz Grafica (UI) usando TOOL_VISION_EVALUATOR, pero no hay modelos de vision instalados.
\
            ADVERTENCIA AL LLM: NO puedes verificar si la UI funciona sin un modelo de vision. NO simules exito.
\
            Debes notificar al usuario que la verificacion visual fallo. Si consideras que el codigo es robusto, evalua saltar la verificacion visual o usar TOOL_ASK_USER para que el usuario valide manualmente.
\
            Prompt original: {}", prompt
        );
        return Err(fallback_msg);
    }

    let model_name = vision_model.unwrap();

    // ── Capture screen ────────────────────────────────────────────────────────
    let base64_img = if let Some(url) = target_url {
        // Enforce headless capture. Do NOT fall back to desktop screenshot
        // because the desktop might just show the IDE/Terminal, causing false positives.
        match capture_headless_browser(url).await {
            Ok(b64) => b64,
            Err(e) => {
                return Err(format!(
                    "[ERROR VISUAL CRITICO] Fallo al capturar la URL '{}'. \
                    Error: {}. \
                    No se puede validar visualmente. NO finjas que la prueba fue exitosa.", 
                    url, e
                ));
            }
        }
    } else {
        let monitors = Monitor::all().map_err(|e| format!("Failed to get monitors: {}", e))?;
        let primary = monitors.first().ok_or("No monitors found")?;
        let image = primary.capture_image().map_err(|e| format!("Failed to capture screen: {}", e))?;
        let mut buffer = Vec::new();
        let mut cursor = std::io::Cursor::new(&mut buffer);
        image.write_to(&mut cursor, image::ImageFormat::Png).map_err(|e| format!("Failed to encode png: {}", e))?;
        STANDARD.encode(&buffer)
    };

    // ── Ask Ollama ────────────────────────────────────────────────────────────
    let client = reqwest::Client::new();
    let payload = json!({
        "model": model_name,
        "prompt": prompt,
        "images": [base64_img],
        "stream": false
    });

    let res = client.post("http://127.0.0.1:11434/api/generate")
        .json(&payload)
        .send()
        .await
        .map_err(|e| format!("Ollama request failed: {}", e))?;

    if res.status().is_success() {
        let response_text = res.text().await.map_err(|e| format!("Failed to read text: {}", e))?;
        let json_val: serde_json::Value = serde_json::from_str(&response_text).map_err(|e| format!("Invalid JSON from Ollama: {}", e))?;
        if let Some(resp) = json_val["response"].as_str() {
            Ok(format!("[VISION QA - {}]: {}", model_name, resp))
        } else {
            Err("Missing 'response' field in Ollama output".to_string())
        }
    } else {
        Err(format!("Ollama API returned {}", res.status()))
    }
}
